#just for tac
statistics=true
job=type_train
jobVersion=0.1
date=2026-03-10 203441395
contextName=Default
jobId=_HnTyoBe7EfG0Wd124CYBIw
jobType=Standard
framework=
projectId=0
applyContextToChildren=false
project=MSPR2
branch=branches/
cmdLineVersion=7.3.1.20200219_1130
